#!/bin/sh

PREREQ=""
prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

OMIT_DRIVERS="qcom_wcnss_pil.ko"

for i in ${OMIT_DRIVERS}; do
    find ${DESTDIR} -name ${i} -delete
done
